### ISSUE TITLE
Screenshots for README

### ISSUE THREAD

**Issue by Falciform-mv** [kimcc/atx-movie-gear#37]
![image](https://user-images.githubusercontent.com/85845397/144144580-5bbd827e-2da1-4a13-b26e-4bfd9e7492ad.png)

![image](https://user-images.githubusercontent.com/85845397/144144623-1e1e3ee1-3eed-41f4-b009-bc61ee1d6232.png)

![image](https://user-images.githubusercontent.com/85845397/144144650-a4cb049f-db91-4564-96b6-410062500f09.png)

**Comment by kimcc** [comment]
Closing as this appears to be complete
